[package]
name = "vyasa-phonetics"
description = "Pre-Pāṇinian, Pāṇinian, and Classical Sanskrit phonetics, sound classifications, and pratyāhāra engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

